/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.openlaunchmc.jestan;

import oshi.SystemInfo;

public class jestan {
    public boolean someLibraryMethod() {
        return true;
    }
}

